language: python
python: "2.7"
install: pip install Sphinx
script: echo "Skipping build..."
before_deploy: wget https://raw.githubusercontent.com/romanvm/travis_scripts/master/publish_docs.py
deploy:
  - provider: script
    script: python publish_docs.py
    skip_cleanup: true
    on:
      branch: master
  - provider: pypi
    user: $PYPI_USER
    password: $PYPI_PASS
    distributions: "sdist bdist_wheel"
    on:
      tags: true
notifications:
  email: false
